# Generated by Django 5.0.6 on 2025-03-12 16:24

import app.candidates.types
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveSmallIntegerField(default=18)),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'MALE'), (2, 'FEMALE'), (3, 'OTHER')], default=app.candidates.types.GenderTypes['MALE'])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(regex='^[6-9][\\d]{9}$')])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
